-include $(TOPDIR)/Make.defs

ASRCS = 
CSRCS = stm32f4xx_hal.c stm32f4xx_hal_adc.c stm32f4xx_hal_adc_ex.c stm32f4xx_hal_cortex.c stm32f4xx_hal_dma.c stm32f4xx_hal_flash.c stm32f4xx_hal_flash_ex.c stm32f4xx_gpio.c stm32f4xx_hal_pwr.c stm32f4xx_hal_pwr_ex.c stm32f4xx_hal_rcc.c stm32f4xx_hal_rcc_ex.c stm32f4xx_hal_spi.c

include $(TOPDIR)/configs/Board.mk
